/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinEssentialTraining

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

/**
 *
 */
fun main(args: Array<String>) {
    val app = App()
    println(app.greeting)

     var num = 9.789;
    val toBigDecimal = num.toBigDecimal();

    toBigDecimal.toDouble();


}
